apache/cordova-common

- src/ConfigChanges/ConfigChanges.js
- src/ConfigChanges/ConfigFile.js
This is to allow customization of the CDVLaunchScreen.storyboard to
adjust contentmode and background color in config.xml.
Further:
I'm not quite sure why the logic is that only some extensions are
recognized as XML and all others as plists. Maybe the opposite would be
better?
Alternatively, an additional parameter to `<config-file>` and
`<edit-config>` to specifiy the file format could be useful.
> CB-13744: Recognize storyboards as XML files

- src/ConfigChanges/ConfigChanges.js
When a file is referenced in `<edit-config>` or `<config-file>` is not found, no warning or error is generated.
This change logs a warning, and includes where the file is actually expected to be based on the filename provided.
@jcaron23 This was your second commit on a previous PR that was asked to be split. The change looks good to me, so I'm opening this so we can get it merged in.
> CB-13770: Warn when <edit-config> or <config-file> not found

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- appveyor.yml
- package.json
- src/superspawn.js
Also added the pull request issue template (copied from cordova-lib) since I noticed that was missing
> CB-14064: Dependency updates & drop node4 CI

- package.json
- spec/fixtures/projects/windows/www/cordova-2.6.0.js
- src/ConfigChanges/ConfigFile.js
- src/ConfigParser/ConfigParser.js
- src/CordovaLogger.js
- src/PlatformJson.js
- src/superspawn.js
- src/util/xml-helpers.js
This replaces most instances of `indexOf` usage with more obvious code; mostly `includes` and `startsWith`. The remaining instances are either in fixtures or really justified.
> Replace indexOf where better alternatives are available

- package.json
- spec/ConfigChanges/ConfigChanges.spec.js
- spec/ConfigChanges/ConfigFile.spec.js
- spec/ConfigParser/ConfigParser.spec.js
- spec/CordovaCheck.spec.js
- spec/FileUpdater.spec.js
- spec/PlatformJson.spec.js
- spec/PluginManager.spec.js
- src/ConfigChanges/ConfigFile.js
- src/ConfigParser/ConfigParser.js
- src/CordovaCheck.js
- src/FileUpdater.js
- src/PlatformJson.js
- src/PluginInfo/PluginInfo.js
- src/PluginInfo/PluginInfoProvider.js
- src/PluginManager.js
- src/superspawn.js
- src/util/xml-helpers.js
Replaces all uses of `shelljs` with `fs-extra` for handling directory creation/deletion and file copying. Replaces the single use of `shelljs.which` with `which`.
While this doesn't have a huge impact here, fs-extra should give us some more stability in our tests in other projects like cordova-lib, especially around directory deletions on Windows.
The potential concern is that these changes will cause test failures in other modules because they are stubbing methods on `fs` instead of `fs-extra`, but my hope would be to update all those other modules as well. I've got a branch of cordova-lib that I've started updating.
> Replace shelljs calls with fs-extra & which

- package.json
All
I just discovered that using plist@3 triggers an unwanted engine warning on Node 4 like this:
```sh
npm WARN engine plist@3.0.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
```
Using plist@2 (plist@^2.1.0) resolves this warning on Node 4 without triggering any `npm audit` warnings at this time.
- `npm test` passes with this change on both Windows and mac development systems
- TODO: test with cordova-android and/or cordova-ios platform in a real Cordova app
- ~~Added automated test coverage as appropriate for this change.~~
> [WIP] package.json use plist@2 to resolve engine warning on node 4 in 2.2.x patch release

- package.json
- src/PlatformJson.js
all
Remove a forgotten dead dependency.
Ticket [CB-12016](https://issues.apache.org/jira/browse/CB-12016) was to remove this dependency and had been resolved but appears `cordova-common` was forgotten.
Tested adding plugins with old and new package name.
> CB-12016: (all) Removed cordova-registry-mapper dependency

- package.json
common (test)
This PR fixes the recent test failures on master branch.
These tests are failing because of the latest Jasmine@3.2.0 that has been released within the past 2 days. (https://github.com/jasmine/jasmine-npm/releases/tag/v3.2.0)
By pinning Jasmine@3.1.0 in package.json, the tests will continue to pass.
🚀 Jasmine@^3.2 Investigation and support will be handled in ticket: https://github.com/apache/cordova-ios/issues/393  (depending on outcome, a separate ticket mat be required for each affect repo.)
- local npm test
- Travis Test
Failed with version up: https://travis-ci.org/cordova-develop/cordova-common/builds/416211005
Fix with version pin: https://travis-ci.org/cordova-develop/cordova-common/builds/416215969
> Pin Jasmine@~3.1.0

- package.json
- spec/PlatformJson.spec.js
- src/PlatformJson.js
Had this lying around. No functional changes besides the formatting of the generated file. Had to modify the tests because of the changed formatting, though.
> Make PlatformJson.generateMetadata more readable

- src/ConfigParser/ConfigParser.js
All
- Add foreground and background attributes to be returned with the get static resources. 
- Ran ESLint
- Ran Jasmine tests
- Ran cordova-android Jasmine Unit-Test. (requires this modification)
- Build default app for Android platform.
> CB-13685 android: Update ConfigParser for Adaptive Icons

- spec/fixtures/test-config0.xml
- spec/util/xml-helpers.spec.js
- src/util/xml-helpers.js
common
This PR is very simple.
Fix xml-helpers graftXML function to create parent element with 'closed tag'.
(i.e.  `'<' + tag_name + '>'` is changed to `'<' + tag_name+ '/>'`)
Because the current cordova-common uses elementtree@0.1.7 which depends on sax@1.1.4,  and the sax@1.1.4 checks 'closed tag' strictly and does not accept 'unclosed tag'.
The old version of cordova-common uses elementtree@0.1.6 which depends on sax@0.3.5, and the sax@0.3.5 checks 'closed tag' loosely. 
We tests this by cordova-ios tests in which pluginHandler.spec.js Test 028 encounters this issue.
Further I added new tests TEST 20-1 in xml-helpers.spec.js in this PR.
> Fix xml-helpers issue by adding close tag

- spec/plist-helpers.spec.js
- src/util/plist-helpers.js
iOS
Resolves an issue where a regex was overly greedy when comparing plist entries for merging and could result in collapsing several of them into a single entry.
Added a test that fails with current master and passes with this change, based on the details provided by @knight9999 in the JIRA bug. It sounds like this might be the cause of GH-44 as well (/fyi @donnie-jp).
Now, my fix assumes that we're always looking for `$(something)` and not just `$something`, which *might* not be a safe assumption. Unfortunately I'm not well-versed enough in iOS stuff to know :(
> CB-13496: Fix greedy regex in plist-helpers

- spec/PluginInfo/PluginInfo.spec.js
- spec/fixtures/plugins/org.test.plugins.withcocoapods/plugin.xml
- src/PluginInfo/PluginInfo.js
ios
- Add new method `getPodSpecs` for `PluginInfo` class
- Add test code
See https://github.com/apache/cordova-discuss/pull/108
- `npm run test`
> add method getPodSpecs and add related tests

- src/CordovaLogger.js
- src/util/formatError.js
Based on the discussion at https://github.com/apache/cordova-lib/pull/721, this attempts to make CordovaLogger a proper singleton, such that we cannot end up with multiple instances of the logger even when multiple versions of cordova-common are in us (of course, that only applies if all those multiple versions are using this singleton pattern)
All existing CordovaLogger tests pass locally.
It would be great to do a test with multiple instances to prove that this singleton pattern works, but I'm not even sure how we'd start setting up a test like that...
> Refactor CordovaLogger to singleton class

- spec/events.spec.js
* Move existing `forwardEventsTo` method tests into `Cordova events` section
* Add Cordova events emit tests
* other minor Cordova events test updates
Motivation:
Without these updates it would be possible for the tests to pass with `return` removed from the following line or the following line completely removed: <https://github.com/apache/cordova-common/blob/6667cfcf1a131b80e09e1410e5166e5f0a420f59/src/events.js#L71>
I think these tests are needed to ensure nothing goes wrong when refactoring events.js into a singleton class as discussed in <https://github.com/apache/cordova-common/pull/53#issuecomment-443561178>.
> Cordova events test updates in spec

- spec/superspawn.spec.js
- src/superspawn.js
At least until Node.js 8, `child_process.spawn` will throw exceptions
instead of emitting error events in certain cases (like EACCES).
To preserve the async nature of `superspawn.spawn` we have to wrap the execution in try/catch to convert the thrown exceptions into rejections.
Added regression test for this bug. Does not run on Windows since the only case I could reproduce this was with an `EACCES` error which usually does not occur in this context there.
> [superspawn] Convert exceptions thrown by child_process.spawn into rejections

- spec/ConfigParser/ConfigParser.spec.js
- src/ConfigParser/ConfigParser.js
None or All, it will not affect any existing code, just provides new APIs
Support set the preference for a specific platform. Currently, only global preference is supported by the `cordova-common`.  We have used the new API to implement a hook which will update platform preference in config.xml
Four unit tests are added. The new added tests don't have `Test ${number}` prefix bc that would lead to a lot of changes in unrelated tests.
> implement setPreference and setPlatformPreference

- src/PluginInfo/PluginInfo.js
none
Complementing docblock for getPodSpecs function
When trying to find more information about new `<podspec>` tag deprecating `<framework type="podspec" />` I found example usage in docblock above getPodSpecs function
However it doesn't specify how to use declarations so I've copied example from [specs fixture](https://github.com/apache/cordova-common/blob/rel/3.1.0/spec/fixtures/plugins/org.test.plugins.withcocoapods/plugin.xml#L37-L47)
Update: Example usage is also described in the [docs](https://cordova.apache.org/docs/en/9.x/plugin_ref/spec.html#podspec-ios).
Change in docblock, no testing required
> Add example usage of podspec declarations

- package.json
All, but hopefully mostly Windows
Hopefully resolves ~~#64~~ _apache/cordova#121 on cordova-common only_
Updated `fs-extra` to the latest version (8.0.0).
`npm test` passed locally on Linux, will ensure it's green on CI.
> Update fs-extra to v8

- spec/ConfigChanges/ConfigChanges.spec.js
- spec/fixtures/projects/ios-config-xml/SampleApp/SampleApp-Info.plist
- src/ConfigChanges/ConfigFile.js
iOS
cordova-ios applies the same formatting already. Neglecting to apply the same here, causes flip-flopping of the file during builds and it's just confusing and inconsistent.
> Fix plist formatting

- appveyor.yml
All
See appveyor/ci#2921: now that AppVeyor has Node.js 12 built-in, we should not ignore failures on that Node.js version.
Remove the lines introduced in PR #68 to ignore AppVeyor failures on Node.js 12
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~
> Do not ignore AppVeyor failures on Node.js 12

- spec/ActionStack.spec.js
- spec/PluginManager.spec.js
- spec/plist-helpers.spec.js
- spec/superspawn.spec.js
Some general Promise handling cleanup in the specs. Nothing exciting. The same patterns I applied in cordova-lib.
Triggered by #74.
> Promise handling cleanup in specs

- package.json
- spec/.eslintrc.yml
- spec/PluginManager.spec.js
- spec/superspawn.spec.js
Replaces #74 together with #79.
> Update to jasmine 3.4 & fix resulting spec failures

- .eslintrc.yml
UPDATED:
- Updated the title
- keeping the custom `no-unused-vars` entry, as requested in the discussion below
- rebased on `master` with force-push after merge of PR #83
As there is desire to keep the custom `no-unused-vars` entry, there seems to be only one exception that we can remove without updating the code. This is why I updated the title and force-pushed the change with the updated commit message.
> remove no-throw-literal lint exception not needed

- .eslintrc.yml
- src/ConfigChanges/ConfigChanges.js
- src/ConfigChanges/ConfigFile.js
- src/PlatformJson.js
- src/PluginInfo/PluginInfo.js
- remove `operator-linebreak` exception from `.eslintrc.yml`
- reformat ternary expresssions according to (semi)standard
- reformat error message expressions according to (semi)standard
as done by the following command, with no `operator-linebreak` exception enabled:
npm run eslint -- --fix
I am breaking this proposal out of PR #82 due to its seemingly controversial nature.
I would really favor applying these fixes, which I think are consistent with both (semi)standard and Prettier styling.
> eslint cleanup fixes: operator-linebreak

- .eslintrc.yml
- package.json
- spec/ConfigChanges/ConfigChanges.spec.js
- spec/ConfigChanges/ConfigFile.spec.js
- spec/CordovaLogger.spec.js
- spec/FileUpdater.spec.js
- spec/PlatformJson.spec.js
- spec/PluginManager.spec.js
- spec/plist-helpers.spec.js
- spec/superspawn.spec.js
- spec/util/xml-helpers.spec.js
- src/ConfigChanges/ConfigChanges.js
- src/ConfigParser/ConfigParser.js
- src/CordovaError/CordovaError.js
- src/CordovaLogger.js
- src/FileUpdater.js
- src/PlatformJson.js
- src/superspawn.js
- src/util/addProperty.js
- src/util/xml-helpers.js
UPDATED after review and discussion:
- ~~merge changes from PR #81 to remove standard eslint exceptions from `.eslint.yml` that are not needed~~
- manual cleanup fix for `no-prototype-builtins` (as needed by new (semi)standard eslint package updates)
- eslint-config-semistandard@14 & eslint-config-standard@13 updates with automatic cleanup fixes (since the `prefer-const` & `quote-props` eslint rules are now enabled)
- automatic eslint cleanup fixes for `padded-blocks` that is no longer kept as an exception
I tried to keep these changes split into separate commits in a semi-sensical manner. I think it would be _a little_ too much to put all these changes into a single commit. I am _now_ proposing _the most important_ changes in _this_ PR for discussion, _with some apparently controversial …
> General cleanup with eslint updates

- src/ConfigChanges/ConfigFile.js
Windows
Fixes #62
Added the file extension `.jsproj` to the allowed extensions for XML files in order to modify such files using the `config-file` tag in the `config.xml`
1. Add the following markup to the `config.xml` inside the `<platform name="windows">` tag:
```
<config-file parent="/Project/PropertyGroup" target="CordovaApp.Windows10.jsproj" versions="10">
<Test>Hello</Test>
</config-file>
```
2. Run `cordova build windows`
_Result without this change:_
The build is aborted with the error message: `malformed document. First element should be <plist>`
_Result with this change:_
The build completes without errors and the `<Test>Hello</Test>` Tag is written to the `CordovaApp.Windows10.jsproj` file.
> (windows) Add .jsproj as file extension for XML files to ConfigFile

- src/CordovaError/CordovaError.js
Alternative to #84 to resolve ESLint `no-proto` rule violation.
Transform the prototype based Class into an ES6 class. The only _potential_ difference in behavior lies in the prototype chain setup. To be safe, this is marked as a breaking change and scheduled for next major.
To review diff, ignore whitespace changes.
Existing tests pass
> [MAJOR] Convert CordovaError to ES6 class

- spec/CordovaError/CordovaError.spec.js
This fix was first introduced in #65 and erroneously reverted by #89.
Fixes #49
> Re-apply fix for failing CordovaError test

- package.json
All
Updated dependencies are generally preferred, in order to reduce the chance of missing security updates in the future.
This PR is raised after checking the results of `npm outdated`, as described in <https://github.com/apache/cordova-coho/blob/master/docs/tools-release-process.md#update-and-pin-dependencies>.
If approved, I think this change should be included in an upcoming minor or major release. I do **not** think this upodate should block the release with fs-extra@8 update (PR #70).
Update to use `strip-bom` version `4` (`^4.0.0`) in `dependencies`
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the …
> [MAJOR] strip-bom@4 update

- spec/PluginInfo/PluginInfoProvider.spec.js
- spec/fixtures/plugins/@scope/test/plugin.xml
- src/PluginInfo/PluginInfoProvider.js
This is the `cordova-common` part of PRs apache/cordova-lib#602 and apache/cordova-lib#680 whose goal is to support scoped npm packages as plugins the same way as regular packages. 
The key difference with scoped packages is that they nested within their `@scope/` directory in the `plugins/` directory. This commit changes `PluginInfoProvider` to honor that fact.
I added an expectation to the unit tests of `PluginInfoProvider`.
> fix: PluginInfoProvider for scoped plugins

- .gitignore
- .npmignore
- package.json
`instanbul` is no longer maintained and we use `nyc` across all other repos.
Closes #72
Drop `instanbul`
Added `nyc` & configs
- `npm t`
> chore: replace instanbul w/ nyc

- .travis.yml
- `codecov` installation and execution in one line thanks to `npx`
- `codecov` only is installed and run if the tests succeed
> ci(travis): run codecov using npx in after_success

- .travis.yml
- package.json
- This is in line with our other repos.
- We don't need to run the tests twice on Travis CI
> test: always run code coverage during `npm test`

- .eslintignore
- .eslintrc.yml
- package.json
- spec/.eslintrc.yml
- spec/ConfigChanges/ConfigChanges.spec.js
- spec/PluginInfo/PluginInfo.spec.js
- src/ConfigChanges/ConfigChanges.js
- src/ConfigParser/ConfigParser.js
- src/PluginInfo/PluginInfo.js
Code syntax cleanup
Closes #73
* replace dependencies with @cordova/eslint-config
* update eslint config
* eslint corrections
- `npm t`
- `npm run eslint`
> refactor: eslint setup

- spec/.eslintrc.yml
ESLint 6.7.0 has just been released and it contains the latest globals
for the jasmine environment. Thus we do not have to add them ourselves.
> style: drop jasmine env workaround

- src/ActionStack.js
- src/ConfigChanges/ConfigChanges.js
- src/ConfigChanges/ConfigFile.js
- src/ConfigChanges/ConfigKeeper.js
- src/ConfigParser/ConfigParser.js
- src/PlatformJson.js
- src/PluginInfo/PluginInfo.js
- src/PluginInfo/PluginInfoProvider.js
- src/PluginManager.js
This applies some of the changes contained in #112. For more information see #113.
Diffs are best reviewed by commit and ignoring whitespace changes.
Applied `lebab --replace src --transform class` to the code and made some adjustments before and after.
> refactor: use classes where applicable

- README.md
- cordova-common.js
Removes `mungeUtil` from the list of modules that are exported by `cordova-common`. It was documented as _internal_ and we did not use it in any of our repos.
> chore!: remove main export mungeUtil

- spec/ConfigChanges/ConfigFile.spec.js
Minor test improvements. Review without whitespace changes.
> test(ConfigFile): group & cleanup tests

- .github/workflows/ci.yml
- .gitignore
- package-lock.json
macOS, Windows, Linux?
This potentially allows us to move away from TravisCI and Appveyor and consolidate all of our CI builds on a single system, which will hopefully be fast to run.
Set up a GitHub Action that runs the tests automatically on Windows, macOS, and Linux (Ubuntu) when a PR is opened. Currently it's testing with node 10 and 12 (as per our plan to drop node 6 and 8).
Should get a bunch of green checkmarks from GitHub...
> TEST: Test using GitHub workflows for CI

- src/PluginInfo/PluginInfo.js
Minor cleanup & simplifications in various modules. Contains changes from #112 and ones that were triggered by me reviewing it.
Simplification without functional changes. See commits for details.
`npm t`
> refactor(PluginInfo): cleanup & simplify

- package-lock.json
- package.json
- spec/CordovaError/CordovaError.spec.js
- src/CordovaError.js
This allows us to properly wrap caught errors in a `CordovaError`:
```js
try {
builder.build(); // throws Error('foo not found')
} catch (err1) {
throw new CordovaError('Build failed', err1));
}
```
Assume we catch above `CordovaError` as `err2`, then we can obtain some nicely formatted information from it:
```js
console.log(err2.message);
```
```
CordovaError: Build failed: foo not found
```
```js
console.log(CordovaError.fullStack(err2));
```
```
CordovaError: Build failed
at ...
at ...
caused by: foo not found
at ...
at ...
```
This is a follow-up to #117. Should preferably be merged after #120.
This commit bases CordovaError on the popular [joyent/node-verror].
We actually use @netflix/nerror, a VError fork for now. That's because
we do not want printf style error formatting support …
> feat(CordovaError): support for error cause & more

- spec/ConfigChanges/ConfigFile.spec.js
- Improves casing of module variable name (`configFile -> ConfigFile`)
- Get fresh module for each test to be able to make proper use of rewire
In preparation of merging #124.
> test(ConfigFile): minor improvements

- spec/ConfigChanges/ConfigChanges.spec.js
- src/ConfigChanges/ConfigFile.js
Glob always returns paths with forward slashes. This change ensures that a config file path obtained from a glob pattern will use the platform-specific path segment separator.
In preparation of merging #124.
> fix(ConfigFile): Normalize globbed file paths

- spec/ActionStack.spec.js
- spec/ConfigChanges/ConfigChanges.spec.js
- spec/ConfigChanges/ConfigFile.spec.js
- spec/ConfigParser/ConfigParser.spec.js
- spec/CordovaCheck.spec.js
- spec/CordovaLogger.spec.js
- spec/FileUpdater.spec.js
- spec/PlatformJson.spec.js
- spec/PluginInfo/PluginInfo.spec.js
- spec/PluginInfo/PluginInfoProvider.spec.js
- spec/PluginManager.spec.js
- spec/plist-helpers.spec.js
- spec/superspawn.spec.js
- spec/util/xml-helpers.spec.js
Modernize code
Use `lebab` to apply `--transform let`. Minimum manual changes for lint fix.
- `npm t`
> refactor: transform var to let/const

- spec/ConfigParser/ConfigParser.spec.js
- src/ConfigParser/ConfigParser.js
The previous `ImageResources` constructor did not cover the case where a single integer argument is given to construct an empty array of the given length. This broke the `map` method since it uses that constructor variant.
This PR fixes that situation by using a static factory method instead of overriding the native Array constructor.
New regression test passes
> fix(ConfigParser): ImageResources constructor

- src/ConfigParser/ConfigParser.js
Cordova iOS Tests failing with latest common because of typos that was introduced in refactor #133.
* `allows_local_networkin` → `allows_local_networking`
* `requires_certificate_transparenc` → `requires_certificate_transparency`
This PR corrects the spelling.
- `npm t`
> fix: typo in access & allow navigation

- spec/ConfigChanges/ConfigFile.spec.js
- src/ConfigChanges/ConfigFile.js
iOS
When multiple plist files exists in a cordova-ios project (e.g. due to a plugin containing `<podspec>`), ConfigFile was updated under CB-5989 to select the app plist as the target for changes destined for *-Info.plist.
However, the change made under CB-5989 incorrectly constructed the path to the app plist by omitting the project name subdirectory from the path, causing the fix to fail to work.
This bug is outlined in #144. 
This commit fixes this by correcting the constructed path to the app plist.
I've created a repo containing a test Cordova project which reproduces the various scenarios to illustrate the issue:
https://github.com/dpa99c/cordova-common-issue-144
Details of these scenarios can be found in [this comment](https://github.com/apache/cordova-common/issues/144#issuecomment …
> fix: resolve correct path to app info plist when multiple plist files are present (#144)

- spec/helper.js
Fixes the following warning:
WARN: jasmine-spec-reporter 'displayStacktrace' option supports value ('none', 'raw', 'pretty'), default to 'none'
And of course shows stack traces for errors during test runs again.
> test: fix invalid config for jasmine-spec-reporter

- .github/workflows/ci.yml
CI
Node 10/12 is now dated and EOL, therefore they have been removed from the matrix. Added Node 16 & 18 for modern test coverage.
Also appears to correct:
```
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Which appears to occur on older Node engines.
CI Matrix change
GH Actions will do it's thing.
> ci: Remove Node 10/12 from matrix. Added Node 16 and 18.

- package-lock.json
- package.json
Simply a bump of the version to 4.1.0-dev to signal next release is a minor.
> chore: 4.1.0-dev

- spec/PluginInfo/PluginInfo.spec.js
- spec/fixtures/plugins/org.test.xmlpassthrough/plugin.xml
- src/PluginInfo/PluginInfo.js
All
Closes https://github.com/apache/cordova-common/pull/179 (superceeds #179)
Currently, adding attributes to the XML tags requires a lot of repos to update.
cordova-common to read the new XML tag.
cordova-lib and cordova cli need to update their dependencies. 
People need to update cordova-cli to have the cordova-common update.
Each platform that wants to use the new attribute needs to be updated.
cordova-docs also needs to be updated.
Depending on the number of platforms that needs the update you're looking at 5 or more repos requiring an update, even when it's simply add a brand new attribute to an XML tag.
This PR updates the XML parsing code to passthrough all attributes.
Existing attributes are parsed in the same way there parsed before. New attributes will be passed through …
> feat(PluginInfo): pass through XML attributes

- package-lock.json
- package.json
- src/superspawn.js
- src/util/plist-helpers.js
- src/util/xml-helpers.js
Drop the entire `underscore` package.
Only a few methods from the package was being used. To reduce the size footprint, I replaced with various lodash modules.
- `_.extend` -> `lodash.assign`
- `_.isDate` -> `lodash.isdate`
- `_.isObject` -> `lodash.isobject`
- `_.zip` -> `lodash.zip`
- `npm t`
> dep: replace underscore w/ lodash module pkgs

- spec/PluginInfo/PluginInfo.spec.js
None
There was a test commented out due to lacking support of passing through XML attributes on preference tags, as documented [here](https://github.com/apache/cordova-common/issues/182), however it was decided that this is not going to be a supported feature.
This pr just removes the commented out test.
Ran npm test
> test: Removed obsolete test

- package.json
- spec/PluginManager.spec.js
- src/ActionStack.js
- src/PluginManager.js
- Replace `q` module with native promises https://github.com/apache/cordova/issues/7
- Closes #76
`superspawn` is not removed and still uses `Q` for `progress` & `notify`.
- `npm t`
> chore: drop q where possible

- src/ConfigParser/ConfigParser.js
- android
Android 13 added support for Themed Icons. Since themed icons aren't yet supported on Cordova Android, adding support for Themed icons inside `cordova-android` required modification to this project as the former project uses `getStaticResources` function defined inside `cordova-common`
https://github.com/apache/cordova-android/issues/1450
Added support for parsing the monochrome icon for Android when preparing / updating the icons.
> android: added monochrome attribute

- .github/workflows/ci.yml
All
CodeQL scanning in CI can help identify bugs and security issues with the library.
* Added CodeQL scanning with default options as part of CI.
* Ran this in my fork, confirmed that CodeQL results showed up under security scanning (and then resolved several of those issues in a previous PR)
> chore(ci): Set up CodeQL analysis

- NOTICE
None
Closes GH-209.
We don't need to include dependencies in the NOTICE that are not installed for end users.
N/A
> chore: Don't list dev dependencies in NOTICE

- package-lock.json
- package.json
- spec/ConfigChanges/ConfigChanges.spec.js
- spec/FileUpdater.spec.js
None
Resolves some deprecations warnings printed to the console in Node 22.
* The `fs.Stats` constructor is deprecated in Node 22 and prints a warning to the console, so we want to find a way to avoid hitting that
* We got some warnings elsewhere that temporary files weren't cleaned up properly after test runs. Try using the `tmp` npm module to handle this better
Ran unit tests locally on Node 22.
> chore: Minor test fixes

- .github/workflows/ci.yml
- .github/workflows/release-audit.yml
all
Improve CI.
* Fix errors when dependabot PRs try to run tests in CI
* Ran in CI, tests pass
> chore(ci): Fix dependabot PR failures

- package-lock.json
- package.json
- spec/CordovaLogger.spec.js
- spec/PluginInfo/PluginInfo.spec.js
- spec/events.spec.js
- src/util/xml-helpers.js
all
nyc doesn't seem to be as actively maintained as we'd like, and pulls in dependencies that have raised licence questions (although they are not distributed as part of the package)
c8 is an alternative that relies on node itself to provide coverage information rather than trying to inject instrumentation into the code
* Move from nyc to c8
* Improve code coverage of a few files
* Replace lodash.zip with an inline version. Lodash no longer recommends using the individual module versions of its packages and instead suggests pulling in the full lodash package, but we literally only need 1 line of code in one place
All tests run, code coverage is generated
> chore(coverage): Move from nyc to c8 for code coverage

- .github/workflows/ci.yml
- .github/workflows/release-audit.yml
n/a
- Add permissions block to GH Actions
- Pin third-party actions to commit hash (per ASF policy)
- `npm t`
> ci: add permissions block & commit hash pinning of third-party actions

- spec/FileUpdater.spec.js
- src/FileUpdater.js
All
Resolves #213
This breaking change wil change the behavior of `<resource-file>`.
`<resource-file>`, as its named,  only supported copying individual files. As far as I am aware, this is how it has always been documented and described.
This PR basically change the understanding of how `resource-file` works. It will now include copying of `directories` and all of its inner content recursively.
This PR will only deal with the recursive copy of directories. Platforms might need to improve its own logic to determine how it should handle what is copied over. 
For example Cordova-iOS would have added each resource file to the pbxproj as resource. With this change, it wont add all files and folders to the pbxproj as resources and it might not add what you expect, depending on how the …
> feat!: change resource-file behavior to support directory contents
