apache/cordova-common

spec/PluginInfo/PluginInfo.spec.js
src/PluginInfo/PluginInfo.js

tests for getFramework/ get framework tag

CB-13145: tests for getFramework

---

spec/fixtures/test-config.xml
src/ConfigParser/ConfigParser.js

Fix as proposed in https://issues.apache.org/jira/browse/CB-13979
I'd like to try to get a unit test written to confirm this fix before merging.

CB-13979: More consistency for config.xml lookups

---

package.json

All
Increment package version to 3.0.0-dev in master branch
Needed due to removal of Node.js 4 support and other possibly breaking changes such as migrating from shelljs to fs-extra
N/A
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

Increment package version to 3.0.0-dev

---

.travis.yml

All
Add vertical spacing, wanted before other changes (npm audit)
CI
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

.travis.yml add spacing

---

src/PluginInfo/PluginInfo.js

ios
This adds attribute for swift support.
https://github.com/apache/cordova-discuss/pull/107
I run 'cordova build' with the ios swift support platform using this cordova-common PR code.

Adding type valued BridgingHeader for swift support.

---

package.json
spec/helper.js
spec/support/jasmine.json

as introduced in cordova-lib by @raphinesse

Verbose test reporter

---

spec/CordovaError/CordovaError.spec.js
spec/superspawn.spec.js

Tests had bugs that had to be fixed.
Fixes #49 
- Fixes unhandled promise in superspawn test
- Removes a test expectation that just is not true and replaces it by something truthy

Test fixes

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/PULL_REQUEST_TEMPLATE.md
package.json
spec/CordovaError/CordovaError.spec.js
spec/superspawn.spec.js

I am including some test & documentation updates from master in the `3.1.x` branch, raising this PR just for the record.

3.1.x branch updates from master

---

src/CordovaError/CordovaError.js

Use Array.prototype.find in CordovaError

---

package.json
spec/ConfigChanges/ConfigChanges.spec.js
spec/PluginManager.spec.js

Remove unused and unneeded dependencies.
* promise-matchers
* osenv
- `npm t`

chore: drop unused & unneeded dependencies

---

package.json
spec/support/jasmine.json

Update jasmine to support latest features.
Updated configs to be consistent with other repo configs.
- `npm t`

chore: update jasmine dependencies & config

---

src/ConfigChanges/ConfigChanges.js
src/ConfigChanges/ConfigKeeper.js
src/ConfigChanges/munge-util.js
src/ConfigParser/ConfigParser.js
src/FileUpdater.js
src/PlatformJson.js
src/PluginInfo/PluginInfo.js
src/PluginManager.js
src/superspawn.js
src/util/xml-helpers.js

While the modernization changes from #112 are _very_ welcome, that PR has been very hard to review because there were so many different refactorings going on simultaneously. So instead of breaking up the refactoring by file, I want to break it up by aspect and do it step by step to yield readable diffs for whenever necessary.
My plan is to follow this PR up with a few more, so that we can finally rebase #112 upon these to see which changes are left in there afterwards.
This PR uses arrow function expressions wherever applicable. Focus is put on minimizing the diff instead of optimizing/formatting the code touched by the diffs.
Code still passes our test suite.

refactor: use arrow functions where applicable

---

src/ConfigChanges/ConfigChanges.js
src/ConfigChanges/ConfigFile.js
src/ConfigChanges/ConfigKeeper.js
src/ConfigParser/ConfigParser.js
src/PluginInfo/PluginInfo.js
src/PluginManager.js
src/events.js

...or _An exercise in being selfless_.
This applies some of the changes contained in #112. For more information see #113.
Marked draft since it requires #113 to be merged first. 
After having switched to arrow functions everywhere in #113, this commit now replaces all `this` aliases with lexical `this`.

refactor: do not alias this to self

---

src/ActionStack.js
src/ConfigChanges/ConfigChanges.js
src/ConfigChanges/ConfigFile.js
src/ConfigChanges/ConfigKeeper.js
src/ConfigChanges/munge-util.js
src/ConfigParser/ConfigParser.js
src/CordovaCheck.js
src/CordovaLogger.js
src/FileUpdater.js
src/PlatformJson.js
src/PluginInfo/PluginInfo.js
src/PluginInfo/PluginInfoProvider.js
src/PluginManager.js
src/superspawn.js
src/util/formatError.js
src/util/plist-helpers.js
src/util/xml-helpers.js

This applies some of the changes contained in #112. For more information see #113.
Applied `lebab --replace src --transform let` to the code with minimal manual changes afterwards.

refactor: transform var to let/const

---

src/ConfigChanges/ConfigChanges.js
src/ConfigParser/ConfigParser.js
src/FileUpdater.js
src/PlatformJson.js
src/PluginInfo/PluginInfo.js

This applies some of the changes contained in #112. For more information see #113.
Marked draft since it requires #113, #114 & #115 to be merged first. Only the last commit belongs to this PR.
Applied `lebab --replace src --transform obj-shorthand` to the code.

refactor: use property shorthand notation

---

src/ActionStack.js
src/ConfigChanges/ConfigChanges.js
src/ConfigChanges/ConfigFile.js
src/ConfigParser/ConfigParser.js
src/FileUpdater.js
src/PlatformJson.js
src/PluginInfo/PluginInfo.js
src/superspawn.js
src/util/formatError.js
src/util/plist-helpers.js
src/util/xml-helpers.js

Some of these changes were also contained in #112.
Marked draft since it requires #113, #114, #115 & #116 to be merged first.
Applied `lebab --replace src --transform template` to the code and made some minor adjustments.

refactor: use template strings where applicable

---

package.json
spec/FileUpdater.spec.js
src/FileUpdater.js

General code readability improvement and reduction.
Should probably be reviewed by commit & ignoring whitespace.
Triggered by #112.
See commits.
Automated tests still pass.

refactor: FileUpdater

---

src/ConfigChanges/munge-util.js

Refactor triggered by me reviewing #112
- simplification without functional changes
- documentation
- type checking
- use modern JS instead of underscore
`npm t`

refactor(munge-util): DRY & simplify

---

package-lock.json

This regenerates `package-lock.json` from scratch as the file that was committed in #95 did not match the dependencies from `package.json`.

fix: broken lock file from #95

---

src/util/xml-helpers.js

Refactor triggered by me reviewing #112
Simplification without functional changes
`npm t`

refactor(xml-helpers): DRY & simplify

---

src/CordovaCheck.js
src/PlatformJson.js
src/util/plist-helpers.js

Minor cleanup & simplifications in various modules. Contains changes from #112 and ones that were triggered by me reviewing it.
Simplification without functional changes. See commits for details.
`npm t`

refactor(misc): cleanup & simplify

---

spec/ConfigParser/ConfigParser.spec.js
src/ConfigParser/ConfigParser.js

Minor cleanup & simplifications in various modules. Contains changes from #112 and ones that were triggered by me reviewing it.
This is the last PR in this series of refactor PRs.
Simplification without functional changes & minor fixes. See commits for details.
`npm t`

refactor(ConfigParser): cleanup & simplify

---

spec/ConfigChanges/ConfigFile.spec.js
src/ConfigChanges/ConfigFile.js

fix(ConfigFile): correct resolve *-Info.plist file path

---

README.md
RELEASENOTES.md
package.json

Various small changes
- `npm t`

chore: various cleanup tasks

---

README.md
package.json

- Apply missing minor changes
- Unify how files are written across repos.

chore: apply random missing minor changes 

---

package-lock.json
package.json

all
resolves a minor `npm audit` warning in devDependencies
see title
- `npm test` passes
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~

update nyc -> ^15.1.0 in devDependencies

---

.asf.yaml
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
CONTRIBUTING.md

all
remove trailing whitespace from the following files:
- `.asf.yaml`
- `.github/ISSUE_TEMPLATE.md`
- `.github/ISSUE_TEMPLATE/BUG_REPORT.md`
- `.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md`
- `CONTRIBUTING.md`
- ran `npm test` in my work area
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~

cleanup: remove trailing whitespace

---

src/ConfigChanges/ConfigChanges.js

Just a tiny code smell I stumbled upon

refactor(ConfigChanges): use for-of loop for iterating over array

---

package-lock.json

none
update `package-lock.json`
rebuilt package-lock.json
n/a

chore: rebuild package-lock.json

---

.github/workflows/ci.yml

n/a
- update `actions/checkout@v3`
- update `actions/setup-node@v3`
- update `codecov/codecov-action@v3`
n/a

ci(actions): update workflow

---

.github/workflows/ci.yml

CI runs on node 14,16,18

---

package-lock.json
package.json

n/a
Prepare for next major release
Bump package version to 5.0.0-dev
n/a

chore: bump version 5.0.0-dev

---

.github/workflows/ci.yml
package-lock.json
package.json

n/a
Bump package requirements
- Drop Node 14 as it will reach EOL by April 2023
- Set Node Requirement to >= 16.0.0
- Set npm requirement to >= 7.10.0 (should be default that comes with node 16.0.0 installation)
- Update CI Workflow
n/a

feat!: bump package requirement node>=16

---

src/util/xml-helpers.js

n/a
Clean up variable name
Renamed variable
n/a

refactor: renamed variable

---

.github/workflows/release-audit.yml
.ratignore
NOTICE
licence_checker.yml

n/a
Add release auditing workflow to CI
Added GitHub Action to run release aduit tools
n/a

ci: add release audit workflow

---

licence_checker.yml

n/a
Fixed a typo in license checker config
removed extra `@`
n/a

chore: fix typo in license checker's ignored-packages config

---

.github/workflows/ci.yml

CI
Node 22 is now available and will become the next LTS release.
Added Node 22 to the CI testing matrix.
Ensured tests run in CI.

chore(ci): Add NodeJS 22 to CI matrix

---

package-lock.json
package.json

Bump for next major
Bump to 6.0.0-dev
N/A

chore: bump 6.0.0-dev

---

spec/PlatformJson.spec.js
spec/PluginInfo/PluginInfo.spec.js
spec/PluginManager.spec.js
spec/fixtures/plugins/org.test.xmlpassthrough/plugin.xml
spec/util/xml-helpers.spec.js
src/PlatformJson.js

Improve test coverage
Also reduces the use of rewire down to just 1 file.
Ran existing and newly added unit tests

chore(tests): Improve test coverage

---

package-lock.json
package.json

n/a
Update remaining npm packages and rebuild `package-lock.json`.
- Bumped `jasmine@5.9.0`
- Rebuilt `package-lock.json`
`npm t`

dep(npm): update w/ rebuilt package-lock.json
